### ISSUE TITLE
update plot_allele_freq? bubble plots are horrible for SNPs

### ISSUE THREAD

**Issue by krshedd** [commfish/GCLr#19]
Who is actively using `plot_allele_freq`? I do not find the bubble plots generated to be particularly informative for SNPs. I suppose they could be helpful for uSATs or microhaps. I'm wondering if we should change the default behavior for `n_alleles == 2` to show a line chart? Or is this just redundant since we have `plot_freq_fis_4snps`?

**Comment by csjalbert** [comment]
I agree it doesn't seem informative for SNPs. The last time I used `Plot_Allele_Freq.GCL` for SNPs, I added a note to the script that says "_Re-run this using a better function -_ `FreqFisPlot4SNPs.GCL`". It may be redundant to include `n_alleles == 2` argument, since we have the other function and seems to work well. What about changing the name to something like `plot_allele_freq_usat`, or simply adding a note or description saying this is not designed for SNPs?

**Comment by csjalbert** [comment]
Thanks, I like the suggested name change - @awbarclay , any objections to renaming this `plot_allele_freq_bubble`? Also, appreciate the additional tags. Details tag lays it out clearly.

**Comment by awbarclay** [comment]
@csjalbert  I have no objections to renaming the function. I think the function was originally intended to look at frequencies for loci with > 2 alleles.

**Comment by awbarclay** [comment]
The function has been renamed plot_allele_freq_bubble
